version: '3.1'

services:
  mysql-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init/01-createTables.sql:/docker-entrypoint-initdb.d/01-createTables.sql
    ports:
      - '3323:3306'

  mysql-seed:
    build: ./init/mysql-seed
    depends_on:
      - mysql-db
    env_file:
      - .env
    volumes:
      - ./init/mysql-seed:/mysql-seed
    working_dir: /mysql-seed
    command: sh seed.sh
